### ISSUE TITLE
Make action

### ISSUE THREAD

**Issue by eggplants** [eggplants/twitter-weathername-action#1]
- <https://docs.github.com/ja/free-pro-team@latest/actions/creating-actions/creating-a-docker-container-action>
- <https://rcmdnk.com/blog/2020/04/23/computer-git-github>

**Comment by eggplants** [comment]
`.github/workflows/main.yml`:
```yml
inputs:
  ar1:
    description: 'arg1'
    required: true
    default: 'ddd'
  ar2:
    required: false
outputs:
  out1: # ${{ steps.jxx.outputs.out1 }}
    description: 'output'
runs:
  using: 'python'
  main: 'main .py'
  args:
    - ${{ inputs.ar1 }}
    - ${{ inputs.ar2 }}
```
